### ISSUE TITLE
Seminar 34 wasn't posted

### ISSUE THREAD

**Issue by moneyball** [sfbitcoindevs/sfbitcoindevs#49]
Can we publish it please? Thanks!

**Comment by EvanWinget** [comment]
@wraithm

**Comment by casey** [comment]
Where are the final links for seminar 34? I see this PR:

https://github.com/sfbitcoindevs/sfbitcoindevs/pull/48

But I'm not sure if it's the final version.

**Comment by wraithm** [comment]
Yeah, I'll get that done today. My bad.

**Comment by EvanWinget** [comment]
I closed my PR and deleted the branch because we didn't end up using it that seminar. @wraithm maybe you can also re-number Socratic 36 -> Socratic 35 when posting the list for 34? Seems like folks didn't think that March was a "real" socratic 😅

**Comment by wraithm** [comment]
> I closed my PR and deleted the branch because we didn't end up using it that seminar. @wraithm maybe you can also re-number Socratic 36 -> Socratic 35 when posting the list for 34? Seems like folks didn't think that March was a "real" socratic 😅

IMHO, we did have a socratic 35. It was just a bit short cuz we had the talk. I might ask Sean for the slides for his talk, and we can post those along with some links that we went over (which was mostly the NY Socratic for March).

**Comment by wraithm** [comment]
We did the Q&A format for like an hour tho!

**Comment by wraithm** [comment]
We basically went through an abbreviated version of this:

https://bitdevs.org/2023-03-29-socratic-seminar-122
