### ISSUE TITLE
August Socratic Seminar Topics

### ISSUE THREAD

**Issue by casey** [sfbitcoindevs/sfbitcoindevs#7]
Suggest topics for the August socratic seminar here! Or ping me on twitter. Or email me. Whatever really.

**Comment by TomW415** [comment]
https://protos.com/researchers-discover-critical-bitcoin-lightning-network-vulnerability/

**Comment by casey** [comment]
Nice, this looks good! I'll include the paper: https://arxiv.org/pdf/2208.01908.pdf
